######################################################################
# Automatically generated by qmake (3.0) Mon Aug 31 01:14:22 2015
######################################################################

TEMPLATE = app
TARGET = try
INCLUDEPATH += .
QT += widgets xml
# Input
HEADERS += exam.h mainwindow.h screenshot.h xbeltree.h
SOURCES += exam.cpp main.cpp mainwindow.cpp screenshot.cpp xbeltree.cpp
